import platform, os

baseEnv = Environment()

if(platform.system() == "Linux"):
   baseEnv.Append( CPPFLAGS = '-std=c++11 -fPIC -finput-charset=iso-8859-2 -Wall -pedantic -pthread -g' )
   baseEnv.Append( LINKFLAGS = '-Wall -pthread' )
   baseEnv.Append( CPPPATH = ['/usr/include/boost'] )
   baseEnv.Append( LIBPATH = ['/usr/lib/x86_64-linux-gnu'] )
   baseEnv.Append( LIBS = ['boost_unit_test_framework', 'boost_regex', 'boost_system','boost_serialization', 'tins'] )

elif(platform.system() == "Windows"):
   baseEnv.Append( CPPFLAGS = ' /EHsc /MD /D "WIN32" /D "_WINDOWS" /W4' )
   baseEnv.Append( CPPPATH = [ 'C:/Boost/boost_1_63_0'] )
   baseEnv.Append( LIBPATH = [ 'C:/Boost/boost_1_63_0/stage/lib'] )

else:
   print platform.system() + " not supported"

baseEnv.Program('Controller', Glob('*.cpp'))
